### PR TITLE
Support web extensions

### PR DESCRIPTION
**Pull request by chrmod**

### CODE REVIEW

**Comment by chrmod** [comment]
@luciancor worked fine for this job, should have no effect for other bootstrap addons http://magrathea:8080/job/addon-repack/45/console.

**Comment by chrmod** [comment]
@luciancor after merge, please update Jenkins job configuration to use master branch again. http://magrathea:8080/job/addon-repack/

**Comment by luciancor** [comment]
@chrmod did you check if the update works properly?

**Comment by chrmod** [comment]
valid point. this version does not handle updates at all. need to generate update xml and change the manifest update url according to https://developer.chrome.com/extensions/autoupdate 
will take care of that

**Pull request merged**
